openai:
  api_key: ${OPENAI_API_KEY}

output:
  base_dir: "data/output"
  jobs_file: "job_listings.csv"
  cover_letters_dir: "cover_letters"

search:
  query: "python developer"
  location: "Poland"

filters:
  keywords:
    - python
    - django
    - flask
  location: "Poland"
  min_salary: 10000

scraping:
  headers:
    User-Agent: "Mozilla/5.0"
  delay: 2  # seconds between requests
